### ISSUE TITLE
deploy game on ropsten

### ISSUE THREAD

**Issue by AkaashMukherjee** [pl4ym0re/tictactoeTuto#19]

**Comment by dabana** [comment]
1) Save game state to the block chain
2) Create an event for the react app to render a change in game state
3) Player connection

**Comment by dabana** [comment]
We will keep it simple for the tutorial:
1) Have an address mapping for checking players in and out
2) Generate and catch an event when the game is over
if we have time
3) Handle draws with the RecoverBet() function
